name: Link check

on:
  pull_request:
  schedule:
    - cron: "0 1 * * 1" # every Monday
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --accept 200,202,403,405,429 --max-retries 3 --timeout 30 README.md countries/*.md
          fail: false
